/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.revature.michael_mcauliffe_p1;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
